DROP DATABASE hsj;
CREATE DATABASE hsj;

USE hsj;

-- 유저 테이블
CREATE TABLE IF NOT EXISTS User (
    id INT AUTO_INCREMENT PRIMARY KEY,
    userId VARCHAR(255) NOT NULL,
    userPw VARCHAR(255) NOT NULL,
    nickname VARCHAR(255),
    createTime TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);