-- 봉사 후기 댓글 테이블
CREATE TABLE Comment (
    id INT PRIMARY KEY,
    ReviewID INT NOT NULL,
    UserID INT NOT NULL,
    context VARCHAR(255),
    createTime TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (id) REFERENCES Review(id) ON DELETE CASCADE,
    FOREIGN KEY (UserID) REFERENCES User(id) ON DELETE CASCADE
);
