spring.application.name=backend
spring.datasource.url=jdbc:mariadb://127.0.0.1:3306/hsj
spring.datasource.username=root
spring.datasource.password=1013
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MariaDBDialect
server.port=25902

spring.jpa.database-platform=org.hibernate.dialect.MariaDBDialect
spring.jpa.show-sql=true

spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl


Front_URL=http://praven.kro.kr

oauth.kakao.client-id=aa593063067708935c526eedf855bc6e
oauth.kakao.redirect-uri=http://praven.kro.kr/auth/callback/kakao
oauth.naver.client-id=entZ4xGkP03kyHMWooKS
oauth.naver.redirect-uri=http://praven.kro.kr/auth/callback/naver


spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=50MB


